# Generated by Django 4.2.11 on 2024-03-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('zip', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('lat', models.DecimalField(decimal_places=5, max_digits=8)),
                ('lng', models.DecimalField(decimal_places=5, max_digits=8)),
                ('city', models.CharField(max_length=100)),
                ('state_name', models.CharField(max_length=100)),
            ],
        ),
    ]
