# Generated by Django 4.2.11 on 2024-03-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('loads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='near_cars',
            field=models.ManyToManyField(related_name='near_cars', to='cars.car'),
        ),
    ]
