# Generated by Django 4.2.11 on 2024-03-25 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loads', '0004_alter_load_near_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='near_cars',
        ),
    ]
