# Generated by Django 4.2.11 on 2024-03-25 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('loads', '0009_remove_load_near_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='loadcarrelation',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_rel', to='cars.car'),
        ),
        migrations.AlterField(
            model_name='loadcarrelation',
            name='load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_rel', to='loads.load'),
        ),
    ]
