# Generated by Django 4.2.11 on 2024-03-26 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('loads', '0010_alter_load_description_alter_loadcarrelation_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadcarrelation',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car'),
        ),
        migrations.AlterField(
            model_name='loadcarrelation',
            name='load',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.load'),
        ),
    ]
